### ISSUE TITLE
Using rauc-hawbit in Buildroot

### ISSUE THREAD

**Issue by hpatriarche** [rauc/rauc-hawkbit#10]
Hello,

We are currently using buildroot on our target and I tried to use rauc-hawkbit-client script.
After upgrading buildroot to install pip tool, I could sort out some module dependencies but it failed on module named 'gi'

 ```
# ./rauc-hawkbit-client -c rauc_hawkbit/config.cfg 
Traceback (most recent call last):
  File "./rauc-hawkbit-client", line 6, in <module>
    import gbulb
  File "/usr/lib/python3.6/site-packages/gbulb/__init__.py", line 1, in <module>
    from .glib_events import *
  File "/usr/lib/python3.6/site-packages/gbulb/glib_events.py", line 12, in <module>
    from gi.repository import GLib, Gio
ModuleNotFoundError: No module named 'gi'
```

and it failed to install pgi:
```
# pip install pgi
Collecting pgi
  Using cached https://files.pythonhosted.org/packages/ed/92/60411ba83f86fa128932466e7ffc86d806d075da64c04d6d45c99a08f4dc/pgi-0.0.11.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_bqklw_w/pgi/setup.py", line 18, in <module>
        import pgi
      File "/tmp/pip-install-_bqklw_w/pgi/pgi/__init__.py", line 10, in <module>
        from .importer import require_version, get_required_version
      File "/tmp/pip-install-_bqklw_w/pgi/pgi/importer.py", line 15, in <module>
        from .clib.gir import GIRepository
      File "/tmp/pip-install-_bqklw_w/pgi/pgi/clib/gir/__init__.py", line 9, in <module>
        from .gibaseinfo import GIInfoType, GIBaseInfo, GIAttributeIter
      File "/tmp/pip-install-_bqklw_w/pgi/pgi/clib/gir/gibaseinfo.py", line 12, in <module>
        from .gitypelib import GITypelib
      File "/tmp/pip-install-_bqklw_w/pgi/pgi/clib/gir/gitypelib.py", line 16, in <module>
        _gir = find_library("girepository-1.0")
      File "/tmp/pip-install-_bqklw_w/pgi/pgi/clib/_utils.py", line 99, in find_library
        _internal[name] = cdll.LoadLibrary(_so_mapping[name])
      File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
        return self._dlltype(name)
      File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: libgirepository-1.0.so.1: cannot open shared object file: No such file or directory

```
python3-gi module is not available ...

Thus, I wonder if anyone tried the rauc-hawkbit in buildroot ? and if there is a fix ?
Also if we move to yocto, does this issue gone ?

Thanks, Herve.

**Comment by Bastian-Krause** [comment]
Hi,

what you are looking for is python-gi/python-gobject. Maybe [this](https://github.com/mathworks/buildroot/blob/master/package/python-gobject/python-gobject.mk) is what you are looking for?

Note that [pgi](https://github.com/pygobject/pgi) is an "experimental/unmaintained" version of it. I don't know if that works..

**Comment by hpatriarche** [comment]
Hi Bastian,

Thanks for you help. 
python-gobject is already available in buildroot, what is missing is python-gi that provide GLib and Gio if I am right.

**Comment by hpatriarche** [comment]
Humm, I tried to remove flag 

> --disable-introspection

then building this package it requires 
```
configure: error: Package requirements (glib-2.0 >= 2.24.0
        gobject-introspection-1.0 >= 0.10.2
    ) were not met:
```
but according to this discussion http://lists.busybox.net/pipermail/buildroot/2017-August/200473.html
it seems pretty difficult to get gobject-introspection package in buildroot.

Thus I guess it is no way to have rauc-hawkbit in buildroot or maybe not with some modules ...

**Comment by Bastian-Krause** [comment]
Hey,

I see - I looked in [ptxdist](https://www.ptxdist.org/) (another build system) and there python3-gi depends on gobject-introspection. I expected the same for buildroot, which is obviously not the case.

There is another promising attempt to get gobject-introspection into buildroot here: https://marc.info/?l=buildroot&m=151803872321668&w=2

I don't know the state of this patch, it does not seem to be upstream yet. Maybe you can test that and maybe even push that attempt forward.

**Comment by Bastian-Krause** [comment]
The current version of this patch is v8, so there is actually some momentum there towards upstream:
https://patchwork.ozlabs.org/cover/950658/

**Comment by ejoerns** [comment]
Did the situation change here?

**Comment by hpatriarche** [comment]
Yes & No !
Still no way to use the python script under Buildroot, so we move to Yocto !

**Comment by ejoerns** [comment]
@hpatriarche too bad, but just saw that gi patch stalled on v5. Unfortunately we do not have Buildroot experts here, too.
If you are not tied to python, maybe it is worth looking at https://github.com/prevas-dk/rauc-hawkbit-updater. And note that PTXdist should support rauc-hawkbit and gi, too, as I have a Demo BSP where it runs successfully in an older version.

I'll update meta-rauc soon to have support for latest rauc-hawkbit master as PR available.

**Comment by ejoerns** [comment]
FTR: https://github.com/rauc/meta-rauc/pull/73

Is it ok for you to close this thread for now?

**Comment by hpatriarche** [comment]
sure
