### ISSUE TITLE
Facing issue while connecting to hawkbit

### ISSUE THREAD

**Issue by khaleelarya** [rauc/rauc-hawkbit#16]
Hi
when i run the rauc-hawkbit-client in my imx6 board it throws the below error

> 2019-01-31 13:48:16 DEBUG    GET http://192.168.1.203:8080//DEFAULT/controller/v1/imx6
2019-01-31 13:48:17 DEBUG    API error: {"timestamp":"2019-02-14T09:18:35.437+0000","status":500,"error":"Internal Server Error","message":"org.s}
2019-01-31 13:48:17 WARNING  Polling failed with a temporary error: 500: Server Error
2019-01-31 13:48:17 INFO     Retry will happen in 60 seconds

my config.cfg file

``` ini
[client]
hawkbit_server = 192.168.1.203:8080
ssl = false
tenant_id = DEFAULT
target_name = imx6
auth_token = 951995949ab159cbc2c7d661ccce98db
mac_address = 98:40:bb:39:ba:f7
bundle_download_location = /tmp/bundle.raucb
log_level = debug
```

Is the configuration ok or am i missing some thing

with ddi api i can able to connect to hawkbit

> curl -X GET http://192.168.1.203:8080/DEFAULT/controller/v1/1233 -H 'Authorization: GatewayToken 951995949ab159cbc2c7d661ccce98db' -H 'Accept: application/hal+json'

**Comment by jmistr01** [comment]
Same issue here. An extra "/" is being added between the http port, and the tenant field in the slug; "DEFAULT" above. 

Workaround:
Edit line 139 in rauc-hawkbit/ddi/client.py
    return '{protocol}://{host}/{api_path}'.format(
Remove "/" between "{host}" and "{api_path}".
    return '{protocol}://{host}{api_path}'.format(

Its terrible but works. 

Is this a change with Hawkbit or the Python client?

**Comment by khaleelarya** [comment]
@jmistr01 
Thanks for your update 
That workaround resolved my issue, Now i can  able to connect my target to hawkbit.

**Comment by Bastian-Krause** [comment]
> Is this a change with Hawkbit or the Python client?

I guess the double slash is in there since the beginning. Seems like HawkBit got pickier since then. Can you open a pull request with the fix?
