### ISSUE TITLE
not getting response of GET request.

### ISSUE THREAD

**Issue by aapurohit** [rauc/rauc-hawkbit#2]
I have installed rauc-hawkbit client on my beaglebone.
My configuration file is : 
[client]
hawkbit_server = 192.168.0.15:8080
ssl = false
ca_file =
tenant_id = DEFAULT
target_name = test
auth_token = ahVahL1Il1shie2aj2poojeChee6ahShu
mac_address = ff:ff:ff:ff:ff:ff
bundle_download_location = /tmp/bundle.raucb
log_level = debug

my hawkbit server is running on my local machine who's ip and port is mentioned at hawkbit server.

on running rauc-hawkbit-client on beaglebone:
DEBUG    Using selector: EpollSelector
DEBUG    GET http://192.168.0.15:8080//DEFAULT/controller/v1/test
WARNING  Polling failed due to TimeoutError
INFO     Retry will happen in 60 seconds

Strangely, this error is occuring only on my beaglebone.

I tried installing rauc-hawkbit on another pc and pc-pc communication is flawless.
Any idea on where am I going wrong or what other things do I need to check?

**Comment by Bastian-Krause** [comment]
Hi,

maybe you are actually running into the timeout as the Hawkbit server on your Beaglebone cannot answer the request in time?

If you notice long response times try increasing the timeout in https://github.com/rauc/rauc-hawkbit/blob/master/rauc_hawkbit/rauc_dbus_ddi_client.py#L34 with something like:
`self.ddi = DDIClient(session, host, ssl, auth_token, tenant_id, target_name, timeout=20)`

Bastian

**Comment by aapurohit** [comment]
Hi thanks for your response,
I have tried increasing the timeout to 50.
Things that I have tried till now are as follows:
1) Installed RAUC hawkbit on pc : Working
2)Sample code for sending get request using aiohttp: Working
3)Installed RAUC hawkbit on beaglebone black : Timeout error
4) Increasing timeout: Timeout error
5)Changing 'url' to generic server eg. http://www.google.com : Timeout error

From the code I have checked that : 
async with self.session.get(url, headers=get_headers,params=query_params) as resp:
                await self.check_http_status(resp)
                json = await resp.json()
                self.logger.debug(json)
                return json
This function is not being executed in the runtime, even after changing parameters of get()

Again any help would be appreciated.

**Comment by Bastian-Krause** [comment]
> 5)Changing 'url' to generic server eg. http://www.google.com : Timeout error

Where exactly did you change that? In rauc_hawkbit/ddi/client.py's get_resource()?

> From the code I have checked that :
> async with self.session.get(url, headers=get_headers,params=query_params) as resp:
> [...]
> This function is not being executed in the runtime, even after changing parameters of get()

You mean everything within the with statement in https://github.com/rauc/rauc-hawkbit/blob/master/rauc_hawkbit/ddi/client.py#L166 ? get_resource is called definitely, because your log output..

> DEBUG GET http://192.168.0.15:8080//DEFAULT/controller/v1/test

..stems from there.

Some questions to get us on the right track:

- Could  you attach the test script you wrote to request resources from your local hawkbit instance including its output?
- Do you use the same hawkbit version on your beaglebone and on your pc?
- Can you access the hawkbit web interface of your beaglebone hawkbit instance?

Bastian

**Comment by aapurohit** [comment]
Sorry for the late reply.
1)The test script I am using is : 
import aiohttp 
import asyncio
async def do_request():
        async with aiohttp.ClientSession() as session:
                async with session.get('http://192.168.0.16:8080//DEFAULT/controller/v1/test') as resp:
                        print(resp.status)
               
loop = asyncio.get_event_loop()
loop.run_until_complete(do_request())

2) Yes I am using the same version of hawkbit on laptop as well as beaglebone.

3) I have not installed or run hawkbit on beaglebone. I am using beaglebone as a client and my laptop as a server. Both the devices are part of the same LAN. 
And yes I recieve 'index.html' for ' wget http://192.168.0.15:8080' (if that was implied)

Thanks 
Aditya

**Comment by Bastian-Krause** [comment]
That is strange. Your test script looks a lot like the code in rauc-hawkbit. I can't spot no important difference. Can you add `with aiohttp.Timeout(10, loop=session.loop):` to your test script and test again?

Did you figure anything out in the meantime?

**Comment by aapurohit** [comment]
Working with with aiohttp.Timeout(10, loop=session.loop):

No I haven't figured out much. 
Could you tell me your test setup in which this library is tested?
Also if it is possible can you recreate my setup and confirm this behaviour.
I am using : 
1) Beaglebone black (AM335) 
2) Debian OS (Jessie) (Non GUI)
3) python 3.5.4

My hawkbit server is set up on my laptop. Laptop and BBB are in the same LAN.

Thanks 
Aditya

**Comment by ejoerns** [comment]
I think I just reproduced it in my demo setup..Will have to have a look at it.

**Comment by ejoerns** [comment]
Could you please compare python3-gbulb versions between the working and the non-working system?

For me, commit [4a15292d55d77240a47f5ab95731ce62c6fa8e37](https://github.com/nathan-hoad/gbulb/commit/4a15292d55d77240a47f5ab95731ce62c6fa8e37) in gbulb seems to fix the issue.
